FROM python:3.9.7

RUN pip install --no-cache-dir --upgrade --prefer-binary redis~=3.5 hiredis~=1.1 simplejson~=3.17 numpy~=1.21 scipy~=1.7 pyroomacoustics~=0.4 Cython~=0.29 pybind11~=2.7

COPY cbsr/common_python /tmp
RUN cd /tmp && python setup.py install && rm -rf *
