<script type="text/javascript">
$(function () {
    $('#startFeed').on('click', function() {
        $.post('start_feed', {id:(username+'-'+devices['cam'])}, function(response){
        	setTimeout(function(){$('#feed').attr('src', 'http://127.0.0.1:8002');}, 100);  
        });
    });
    $('#stopFeed').on('click', function() {
    	$('#feed').attr('src', '');
        $.post('stop_feed', {id:(username+'-'+devices['cam'])});
    });
});
</script>
<h3>Control</h3>
<div id="feedForm" class="form-inline mb-3">
	<img id="feed" class="mb-3">
  	<button id="startFeed" type="submit" class="btn btn-primary ml-1">Start watching</button>
  	<button id="stopFeed" type="submit" class="btn btn-primary ml-1">Stop watching</button>
</div>
<form id="sayForm" class="form-inline">
	<div class="form-group"><input type="text" class="form-control" name="say"></div>
  	<button type="submit" class="btn btn-primary ml-1">Say</button>
</form>