<script type="text/javascript">
$(function () {
    $('#startFeed').on('click', function() {
        $.post('start_feed', {id:(username+'-'+devices['cam'])}, function(response){
        	setTimeout(function(){$('#feed').attr('src', 'http://127.0.0.1:8002');}, 100);  
        });
    });
    $('#stopFeed').on('click', function() {
    	$('#feed').attr('src', '');
        $.post('stop_feed', {id:(username+'-'+devices['cam'])});
    });
    var idle = false;
    $('#toggleIdle').on('click', function() {
        if(idle) {
    		$.post('command', {id:(username+'-'+devices['robot']), cmd:'action_idle', data:'false'});
			idle = false;
        } else {
    		$.post('command', {id:(username+'-'+devices['robot']), cmd:'action_idle', data:'true'});
			idle = true;
        }
    });
    $('#sayForm').on('click', ':submit', function() {
        var form = $('#sayForm');
        var name = $(this).val();
        var data = form.serializeArray();
        $.post('command', {id:(username+'-'+devices['speaker']), cmd:('action_'+name), data:(data[0].value)});
        form.trigger('reset');
        return false;
    });
    var allGestures = {};
    $.getJSON('gestures.json', function(data) {
		allGestures = data;
    });
    $('#animForm').on('submit', function() {
        var popup = $('#popup');
        var content = $('#popupContent');
        $.each(allGestures, function(name,value) {
			content.append('<button type="submit" value="'+value+'" class="btn btn-primary ml-1 mb-1">'+name+'</button>');
        });
        content.on('click', ':submit', function() {
            var anim = $(this).val();
        	$.post('command', {id:(username+'-'+devices['robot']), cmd:'action_gesture', data:anim});
        	popup.modal('hide');
        });
        popup.on('hidden.bs.modal', function (e) {
            content.empty();
        });
    	popup.modal('show');
		return false;
    });
    var allColours = {'White':'#FFFFFF', 'Red':'#FF0000', 'Green':'#008000', 
    	    'Blue':'#0000FF', 'Yellow':'#FFFF00', 'Magenta':'#FF00FF', 'Cyan':'#00FFFF'};
    $('#eyeForm').on('submit', function() {
        var popup = $('#popup');
        var content = $('#popupContent');
        $.each(allColours, function(name,code) {
			content.append('<button type="submit" value="'+name+'" class="btn btn-primary ml-1 mb-1" style="color:#202020;background-color:'+code+'">'+name+'</button>');
        });
        content.on('click', ':submit', function() {
            var colour = $(this).val().toLowerCase();
        	$.post('command', {id:(username+'-'+devices['robot']), cmd:'action_eyecolour', data:colour});
        	popup.modal('hide');
        });
        popup.on('hidden.bs.modal', function (e) {
            content.empty();
        });
    	popup.modal('show');
		return false;
    });
});
</script>
<h3>Control</h3>
<form id="eyeForm" class="float-right">
  	<button type="submit" class="btn btn-primary ml-1">Eye Colour</button>
</form>
<div id="feedForm" class="form-inline mb-3">
	<img id="feed" class="w-100 mb-3">
  	<button id="startFeed" type="submit" class="btn btn-primary ml-1">Start watching</button>
  	<button id="stopFeed" type="submit" class="btn btn-primary ml-1">Stop watching</button>
  	<button id="toggleIdle" type="submit" class="btn btn-primary ml-1">Toggle idle</button>
</div>
<form id="animForm" class="float-right">
  	<button type="submit" class="btn btn-primary ml-1">Gesture</button>
</form>
<form id="sayForm" class="form-inline mb-3">
	<div class="form-group"><input type="text" class="form-control" name="say"></div>
  	<button type="submit" value="say" class="btn btn-primary ml-1">Say</button>
  	<button type="submit" value="say_animated" class="btn btn-primary ml-1">Say (anim)</button>
</form>