<script type="text/javascript">
$(function () {
	$('#customFile').on('change', function(e) {
		var files = e.target.files;
		if(files.length < 1) {
			return false;
		}
		var file = files.item(0);
		$('#customFileLabel').html(file.name);
		var fr = new FileReader();
		fr.onload = function(e) {
			var config = JSON.parse(e.target.result);
			var favs = $('#favs');
			favs.off();
			favs.empty();
			$.each(config, function(i, entry) {
				if(entry.type === 'header') {
					var header = '<h6 class="w-100 mt-1">'+entry.text+'</h6>';
					favs.append(header);
				} else if(entry.type === 'button' || entry.type === 'field') {
					var isField = (entry.type === 'field');
					if(isField) {
						var input = '<input type="text" class="form-control">';
						favs.append(input);
					}
    				var id = 'fav'+i;
    				var style = entry.hasOwnProperty('style') ? entry.style : 'primary';
    				var button = '<button type="submit" class="btn btn-'+style+' ml-1 mb-1" id="'+id+'">'+entry.name+'</button>';
    				favs.append(button);
    				$('#'+id).on('click', function() {
    					var type = 'robot';
    					if(entry.action.startsWith('action_say') || entry.action.startsWith('action_speech') ||
    	    					entry.action.startsWith('audio_') || entry.action === 'action_stop_talking') {
    						type = 'speaker';
    					} else if(entry.action === 'render_html') {
    						type = 'browser';
    					}
    					var data = isField ? $(this).prev().val() : entry.data;
    					$.post('command', {id:(username+'-'+devices[type]), cmd:entry.action, data:data});
    					if(isField) $(this).prev().val('');
    				});
				}
			});
		}
		fr.readAsText(file);
		$(this).val(null);
	});
});
</script>
<h3>Favourites</h3>
<div class="custom-file mb-3">
  <input type="file" class="custom-file-input" id="customFile" accept=".json">
  <label class="custom-file-label" for="customFile" id="customFileLabel">Config</label>
</div>
<div id="favs" class="form-inline"></div>