<script type="text/javascript">
$(function () {
    $('#settingsForm').on('submit', function() {
        $.post('settings', $(this).serialize(),
                function(response){$('#popupContent').html('<pre>'+response+'</pre>');$('#popup').modal();});
        return false;
    });
    $('#robotLogs').on('click', function() {
        $.get('robot_logs', {}, function(response){$('#popupContent').html('<pre>'+response+'</pre>');$('#popup').modal();});
        return false;
    });
    $('#robotQuit').on('click', function() {
        $.post('robot_disconnect', {}, function(response){$('#popupContent').html('<pre>'+response+'</pre>');$('#popup').modal();});
        return false;
    });
});
</script>
<h3>CBSR Settings</h3>
<form id="settingsForm" class="mt-4">
  <div class="form-group">
    <label for="myIp">My IP address:</label>
    <input type="text" class="form-control" name="myIp" aria-describedby="myIpHelp" value="<?= $_SESSION['myIp'] ?? '' ?>">
    <small id="myIpHelp" class="form-text text-muted">Please enter the LAN IP address of your device.</small>
  </div>
    <div class="form-group">
    <label for="myUser">My Username:</label>
    <input type="text" class="form-control" name="myUser" aria-describedby="myUserHelp" value="<?= $_SESSION['myUser'] ?? '' ?>">
    <small id="myUserHelp" class="form-text text-muted">Please enter your username.</small>
  </div>
    <div class="form-group">
    <label for="myPass">My Password:</label>
    <input type="password" class="form-control" name="myPass" aria-describedby="myPassHelp" value="<?= $_SESSION['myPass'] ?? '' ?>">
    <small id="myPassHelp" class="form-text text-muted">Please enter your password.</small>
  </div>
  <div class="form-group">
    <label for="robotIp">Robot IP address:</label>
    <input type="text" class="form-control" name="robotIp" aria-describedby="robotIpHelp" value="<?= $_SESSION['robotIp'] ?? '' ?>">
    <small id="robotIpHelp" class="form-text text-muted">Enter the LAN IP-address of the Nao/Pepper (if used)</small>
  </div>
  <div class="form-group">
    <label for="robotPass">Robot Password:</label>
    <input type="text" class="form-control" name="robotPass" aria-describedby="robotPassHelp" value="<?= $_SESSION['robotPass'] ?? '' ?>">
    <small id="robotPassHelp" class="form-text text-muted">Enter the password for the Nao/Pepper (if used)</small>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
  <a href="#" id="robotLogs" style="float:right; margin-top:2%;">Robot Logs</a>
  <a href="#" id="robotQuit" style="float:right; margin-top:2%;margin-right:10%;">Disconnect</a>
</form>